version: "3.9"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    links:
      - mysql:mysql
  mysql:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - .docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=root